
name: Test
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    container: rust:1-buster
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin --out Xml
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}