
name: Test
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/glovebox-environment:temp
      # image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin --out Lcov --output-dir=./coverage/
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}