
name: Test
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    container: rust:1-buster
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cargo build --tests
      - run: cargo test
